<?php 
$data = [
	'theme'=>[
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/1morningIU.png",
			"active"=>"https://tdream.antit.top/1morningIA.png",
			"title"=>"早起",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/2readbookIU.png",
			"active"=>"https://tdream.antit.top/2readbookIA.png",
			"title"=>"看书",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/3SleepEarlyIU.png",
			"active"=>"https://tdream.antit.top/3SleepEarlyIA.png",
			"title"=>"早睡",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/4wordIU.png",
			"active"=>"https://tdream.antit.top/4wordIA.png",
			"title"=>"记单词",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/5drinkingIU.png",
			"active"=>"https://tdream.antit.top/5drinkingIA.png",
			"title"=>"喝水",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/6drawingIU.png",
			"active"=>"https://tdream.antit.top/6drawingIA.png",
			"title"=>"画画",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/7practisecalligraphyIU.png",
			"active"=>"https://tdream.antit.top/7practisecalligraphyIA.png",
			"title"=>"练字",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/8diaryIU.png",
			"active"=>"https://tdream.antit.top/8diaryIA.png",
			"title"=>"写日记",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/9breakfastIU.png",
			"active"=>"https://tdream.antit.top/9breakfastIA.png",
			"title"=>"吃早餐",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/10fitnessIU.png",
			"active"=>"https://tdream.antit.top/10fitnessIA.png",
			"title"=>"健身",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/11loseweightIU.png",
			"active"=>"https://tdream.antit.top/11loseweightIA.png",
			"title"=>"减肥",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/12photographIU.png",
			"active"=>"https://tdream.antit.top/12photographIA.png",
			"title"=>"拍照",
		],
		// [
		// 	"check"=>true,
		// 	"normal"=>"https://tdream.antit.top/5drinkingIU.png",
		// 	"active"=>"https://tdream.antit.top/5drinkingIA.png",
		// 	"title"=>"其他",

		// ],
	],
	'theme_type'=>[//主题类型
		'main'=>[
			'exercise'=>"运动健身",
			'english'=>"英语",
			'art'=>"艺术",
			'work'=>"创业/职场",
			'life'=>"生活",
		],
		'sub'=>[
			'健身'=>'exercise',
            '减肥'=>'exercise',
            '记单词'=>'english',
            '画画'=>'art',
            '看书'=>'work',
            '早起'=>'life',
            '早睡'=>'life',
            '喝水'=>'life',
            '吃早餐'=>'life',
            '练字'=>'life',
            '写日记'=>'life',
		]
	],
	'feedback'=>[//用户反馈
		[
			'headicon'=>'https://tdream.antit.top/tx_20190422233756.png',
			'title'=>"大三学生",
			'username'=>'张玲',
			'content'=>"马上就要参加英语六级考试了，却迟迟没有开始准备，这次参加追梦行动派行动合约，终于开始行动了，每天早起读英语背单词快一个月了，真的很有成就感，既学习了又养成了早起的好习惯，Nice！"
		],
		[
			'headicon'=>"https://tdream.antit.top/image/icon03.png",
			'title'=>"公司白领",
			"username"=>"瑞丽",
			'content'=>"说出来挺不好意思的，春节前和一位男士相亲，还没有与对方见面，就被推辞了，据说理由是对方看我照片觉得有点胖，话说我还专门P一下的，这下可真是受打击了，必须减肥，已经加入追梦行动合约8天，哼，见证我的蜕变吧！"
		],
		[
			'headicon'=>"https://tdream.antit.top/image/icon02.png",
			'title'=>"正在做软件设计的",
			"username"=>"肖欢",
			'content'=>"以前大学时有一个特别喜欢的女朋友，但是由于我乱发脾气，每次都让她受委屈，最后她终于和我分手了，我特别伤心，我很这次加入追梦行动100天合约已经有二十多天了，希望坚持不发脾气，养成良好的沟通相处习惯！"
		],
		[
			'headicon'=>"https://tdream.antit.top/image/icon01.png",
			'title'=>"刚刚退休的大学教授",
			'username'=>"徐老",
			'content'=>"快坚持半个月了，好多年前就说和几个老哥一起去大峡谷探险，到今天也没约起来，事真
			的越来越多，这次我的学生邀请我加入追梦行动派挑战百天合约，瞬间觉得自己变年轻了，
			坚持早起锻炼，身体练好了去实现多年的探险梦想！"
		],
		[
			'headicon'=>"https://tdream.antit.top/image/icon04.png",
			'title'=>"外企工作1年的",
			"username"=>"刘冰",
			'content'=>"大学刚毕业时就说要考雅思，一直没顾上，这次公司要在海外做一个高奖金的优质旅游
			项目，外派的员工指标中英语雅思是基础，我希望通过参加行动合约，能逼自己一把，坚持
			学习英语，争取顺利通过考试！"
		],
		[
			'headicon'=>"https://tdream.antit.top/image/icon05.png",
			'title'=>"金融行业的高层",
			"username"=>"余叶",
			'content'=>"参加行动合约已有18天，说实话坚持100天确实很有挑战，但也非常刺激，这次如果能坚持学习100天，相信通过北航的MBA考试不在是梦。"
		],
	],
	'cattention'=>[//合约注意事项
		'CO0000000001'=>"<p class='warm_txt'>1.返现机制：每天完成打卡返现1元，连续完成21天再返77元，打卡中断则停止返现</p><p class='warm_txt'>2.打卡时间：北京时间24点前进入平台点击打卡有效；从支付第二天开始计算</p>",
		'CO0000000002'=>"<p class='warm_txt'>1.支付后24小时内可申请无理由退款</p><p class='warm_txt'>2.平台打卡后，分享朋友圈(所有人可见且返现之前不可删除)，连续100天未中断，则合约结束后一周内返还200元</p><p class='warm_txt'>3.北京时间24点前进入平台打卡并分享朋友圈算有效；从支付第二天开始计算</p>"
	]
];
?>

