<?php 
$data = [
	'theme'=>[
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/1morningIU.png",
			"active"=>"https://tdream.antit.top/1morningIA.png",
			"title"=>"早起",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/2readbookIU.png",
			"active"=>"https://tdream.antit.top/2readbookIA.png",
			"title"=>"看书",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/3SleepEarlyIU.png",
			"active"=>"https://tdream.antit.top/3SleepEarlyIA.png",
			"title"=>"早睡",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/4wordIU.png",
			"active"=>"https://tdream.antit.top/4wordIA.png",
			"title"=>"记单词",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/5drinkingIU.png",
			"active"=>"https://tdream.antit.top/5drinkingIA.png",
			"title"=>"喝水",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/6drawingIU.png",
			"active"=>"https://tdream.antit.top/6drawingIA.png",
			"title"=>"画画",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/7practisecalligraphyIU.png",
			"active"=>"https://tdream.antit.top/7practisecalligraphyIA.png",
			"title"=>"练字",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/8diaryIU.png",
			"active"=>"https://tdream.antit.top/8diaryIA.png",
			"title"=>"写日记",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/9breakfastIU.png",
			"active"=>"https://tdream.antit.top/9breakfastIA.png",
			"title"=>"吃早餐",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/10fitnessIU.png",
			"active"=>"https://tdream.antit.top/10fitnessIA.png",
			"title"=>"健身",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/11loseweightIU.png",
			"active"=>"https://tdream.antit.top/11loseweightIA.png",
			"title"=>"减肥",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/12photographIU.png",
			"active"=>"https://tdream.antit.top/12photographIA.png",
			"title"=>"拍照",
		],
		// [
		// 	"check"=>true,
		// 	"normal"=>"https://tdream.antit.top/5drinkingIU.png",
		// 	"active"=>"https://tdream.antit.top/5drinkingIA.png",
		// 	"title"=>"其他",

		// ],
	],
	'feedback'=>[//用户反馈
		[
			'headicon'=>"",
			'username'=>"",
			'content'=>""
		],
		[
			'headicon'=>"",
			'username'=>"",
			'content'=>""
		],
	],
	'cattention'=>[//合约注意事项
		'CO0000000001'=>"<p>1.返现机制：每天完成打卡返现1元，连续完成21天再返77元，打卡中断则停止返现</p><p>2.打卡时间：北京时间24点前进入平台点击打卡有效；从支付第二天开始计算</p>",
		'CO0000000002'=>"<p>1.支付24小时内可申请无理由退款</p><p>2.平台打卡后，分享朋友圈(所有人可见且返现之前不可删除)，连续100天未中断，则合约结束后一周内返还200元</p><p>3.北京时间24点前进入平台打卡并分享朋友圈算有效；从支付第二天开始计算</p>"
	]
];
?>

