<?php 
$data = [
	'theme'=>[
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/1morningIU.png",
			"active"=>"https://tdream.antit.top/1morningIA.png",
			"title"=>"早起",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/2readbookIU.png",
			"active"=>"https://tdream.antit.top/2readbookIA.png",
			"title"=>"看书",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/3SleepEarlyIU.png",
			"active"=>"https://tdream.antit.top/3SleepEarlyIA.png",
			"title"=>"早睡",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/4wordIU.png",
			"active"=>"https://tdream.antit.top/4wordIA.png",
			"title"=>"记单词",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/5drinkingIU.png",
			"active"=>"https://tdream.antit.top/5drinkingIA.png",
			"title"=>"喝水",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/6drawingIU.png",
			"active"=>"https://tdream.antit.top/6drawingIA.png",
			"title"=>"画画",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/7practisecalligraphyIU.png",
			"active"=>"https://tdream.antit.top/7practisecalligraphyIA.png",
			"title"=>"练字",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/8diaryIU.png",
			"active"=>"https://tdream.antit.top/8diaryIA.png",
			"title"=>"写日记",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/9breakfastIU.png",
			"active"=>"https://tdream.antit.top/9breakfastIA.png",
			"title"=>"吃早餐",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/10fitnessIU.png",
			"active"=>"https://tdream.antit.top/10fitnessIA.png",
			"title"=>"健身",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/11loseweightIU.png",
			"active"=>"https://tdream.antit.top/11loseweightIA.png",
			"title"=>"减肥",
		],
		[
			"check"=>false,
			"normal"=>"https://tdream.antit.top/12photographIU.png",
			"active"=>"https://tdream.antit.top/12photographIA.png",
			"title"=>"拍照",
		],
		// [
		// 	"check"=>true,
		// 	"normal"=>"https://tdream.antit.top/5drinkingIU.png",
		// 	"active"=>"https://tdream.antit.top/5drinkingIA.png",
		// 	"title"=>"其他",

		// ],
	],
	'feedback'=>[//用户反馈
		[
			'headicon'=>"",
			'username'=>"",
			'content'=>""
		],
		[
			'headicon'=>"",
			'username'=>"",
			'content'=>""
		],
	],
	'cattention'=>[//合约注意事项
		'CO0000000001'=>"<p></p><p></p>",
		'CO0000000002'=>"<p></p><p></p>"
	]
];
?>

