UPDATE `publicaccounts` SET `description`="吉他、尤克里里、钢琴凳多种乐器教学，学乐器上Finger！Follow Finger Anyone Can Play！" WHERE `title`="Finger"
UPDATE `publicaccounts` SET `description`="Keep，1.6亿运动爱好者都在用的App。关注@Keep：健身方式、饮食建议、用户蜕变，尽在指尖。" WHERE `title`="keep"
UPDATE `publicaccounts` SET `description`="智能健身，科技让运动更有效。" WHERE `title`="VIPKID"
UPDATE `publicaccounts` SET `description`="VIP陪练——线上专业真人老师一对一音乐陪练平台。来自各个国家数万名琴童家长的选择。" WHERE `title`="VIP陪练"
UPDATE `publicaccounts` SET `description`="中国首创的每月129元/199元/299元(已入住北京、上海、杭州、南京、济南、深圳、重庆、武汉8大城市)，按月支付，不限课次不限使用次数的互联网+健身房，7天×24小时营业，每月 300 节团操课任选，全国已经入驻近500家。" WHERE `title`="乐刻运动"
UPDATE `publicaccounts` SET `description`="随时随地，听我想听。" WHERE `title`="喜马拉雅FM"
UPDATE `publicaccounts` SET `description`="提供省时间的知识服务。" WHERE `title`="得到"
UPDATE `publicaccounts` SET `description`="智能健身，科技让运动更有效。" WHERE `title`="快快智能健身"
UPDATE `publicaccounts` SET `description`="悦跑圈是一款跑步+社交相融合的国内专业跑步 APP。中国田径协会线上马拉松唯一战略合作伙伴。致力于为用户打造一个最纯净的跑步这社区。2015 年及 2016 年度均被权威评选为年度最佳跑步APP" WHERE `title`="悦跑圈"
UPDATE `publicaccounts` SET `description`="1800万用户的听书选择，每周一小时，听懂一本书。" WHERE `title`="樊登读书"
UPDATE `publicaccounts` SET `description`="混沌大学公众平台，创新加的思想汇，混沌新鲜事的集散地，和你一起面向未来。" WHERE `title`="混沌大学"
UPDATE `publicaccounts` SET `description`="百词斩是有图片的背单词利器哦！我们为每个单词精心挑选图片，配以斩家英文母语使用者老外人肉撰写、朗读的例句，新增2000+象形单词和10000+词根解析(不断增加中)，让背单词不再痛苦。" WHERE `title`="百词斩"
UPDATE `publicaccounts` SET `description`="第一时间为你提供美术联考、校考咨询、教程干货，为你私人定制美术内容，美术生必备神器！" WHERE `title`="美术宝"
UPDATE `publicaccounts` SET `description`="作为国内建立最早的舞蹈网站，建立10年多年来一直致力于舞蹈事业的传播与普及，拥有数几十万舞蹈会员。" WHERE `title`="舞蹈网"
UPDATE `publicaccounts` SET `description`="让你忍不住，开口说英语。" WHERE `title`="英语流利说"
UPDATE `publicaccounts` SET `description`="荔枝微课，成长每时每刻。海量优质课程，大咖讲师聚集，点击右下方”关注“，现在开始，成为更好的自己。" WHERE `title`="荔枝微课"
UPDATE `publicaccounts` SET `description`="欢迎加入馒头商学院(www.mtedu.com)，互联网从业者在线学习社群！这里汇集众多优秀的产品、运营、营销大咖，提供接地气的实战课程。你还可以记入各种专业小组，收获导师、朋友圈子，与优秀的互联网人一起成长！" WHERE `title`="馒头商学院"